### ISSUE TITLE
Issue clean install using maven for ctakes-ytex

### ISSUE THREAD

**Issue by Haags** [apache/ctakes#8]
I was wondering if anybody had any advice for me on the following error, I am trying to clean install from the head of the main branch in git.

Below are my commands; this error start with commit d998331c1cfef48d792c78a8d3c1670498a8b925
The commands below work for the previous commit a97258b01d455f7816994070cf64deb311b29acc

steps to reproduce 
git clone the ctakes repo

mvn clean install -ff -DskipTests=true;

error message
/root/projects/ctakes/ctakes-ytex/scripts/build-setup.xml:149: The following error occurred while executing this line:
[ERROR] /root/projects/ctakes/ctakes-ytex/scripts/data/build.xml:148: The following error occurred while executing this line:
[ERROR] /root/projects/ctakes/ctakes-ytex/scripts/data/build.xml:531: Warning: Could not find file /root/projects/ctakes/ctakes-ytex/scripts/data/${project.basedir}/conn.xml.template to copy.

mvn -v
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 1.8.0_282, vendor: AdoptOpenJDK, runtime: /opt/java/openjdk/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.147+", arch: "amd64", family: "unix"

**Comment by seanfinan** [comment]
Hi Scott,

Thanks for the report - especially the setup, failure message and commit details.  Would you mind copying it into the GitHub issues area?  https://urldefense.com/v3/__https://github.com/apache/ctakes/issues__;!!NZvER7FxgEiBAiR_!r_NQsbbnDqD-QGMwq_ofjWAsCeeR1pGVKoB2EVnideNr2t6t24yCwJmoibSXDSf6F40_bEadTeF5AGH5NItUpOBViKAQtNUFoJM9wlumGFqmeqbv-A$

I think that I know what happened ...

The pom files for several modules used ${basedir} instead of the preferred ${project.basedir}.  I updated them to standard.  I also changed ${basedir} in the ytex scripts and apparently, they don't have substitution for that expression.  I will have it fixed in a few minutes and try again.

Sean

**Comment by seanfinan** [comment]
I just checked in the revert on ctakes-ytex/scripts/data/build.xml
Packaging works on my machine, but it had also worked for all previous tests so reopen if this is still an issue.
Sean

**Comment by Haags** [comment]
I tested and it works now for me, thank you!
